% This script plots the equilibrium disease burdens for the different
% transmission structures in the UK under mumps-like disease parameters.
% These plots are in Figure 3 of the paper and Figure 1 of the supplement.

load('Parameters/UK_MixingData.mat'); % Contains d_ext, d_int, ClassProb, D_All, D_Ext, E, NGrid, tickGrid, DemGrid

load('Parameters/UKDemography.mat');

load('ModelOutput/UKStructureEqDists.mat');

[Cond_young,Cond_old,h_UKHom_C]=Get_Prevalence_Histogram...
    ( nVect,nTicker,kB,kL,Equil_Hom,DiseaseFree,'UKHomHist_Cond','Homogeneous Mixing','y_max',0.25 );
[~,~,h_UKPOLY_C]=Get_Prevalence_Histogram...
    ( nVect,nTicker,kB,kL,Equil_POLY,DiseaseFree,'UKPOLYHist_Cond','Age-Structured Mixing',...
    'y_max',0.25,'YOutline',Cond_young,'OOutline',Cond_old );
[~,~,h_UKHH_C]=Get_Prevalence_Histogram...
    ( nVect,nTicker,kB,kL,Equil_HH,DiseaseFree,'UKHHHist_Cond','Household-Structured Mixing',...
    'y_max',0.25,'YOutline',Cond_young,'OOutline',Cond_old );
[~,~,h_UKFull_C]=Get_Prevalence_Histogram...
    ( nVect,nTicker,kB,kL,Equil_Full,DiseaseFree,'UKFullHist_Cond','Full Model',...
    'y_max',0.25,'LEGEND','on','young_max',4,'old_max',3,'YOutline',Cond_young,'OOutline',Cond_old );

[Unco_young,Unco_old,h_UKHom_UC]=Get_Prevalence_Histogram...
    ( nVect,nTicker,kB,kL,Equil_Hom,DiseaseFree,'UKHomHist_Unco','Homogeneous Mixing','y_max',0.02,...
    'CONDITIONAL','abs');
[~,~,h_UKPOLY_UC]=Get_Prevalence_Histogram...
    ( nVect,nTicker,kB,kL,Equil_POLY,DiseaseFree,'UKPOLYHist_Unco','Age-Structured Mixing',...
    'y_max',0.02,'YOutline',Unco_young,'OOutline',Unco_old,...
    'CONDITIONAL','abs');
[~,~,h_UKHH_UC]=Get_Prevalence_Histogram...
    ( nVect,nTicker,kB,kL,Equil_HH,DiseaseFree,'UKHHHist_Unco','Household-Structured Mixing',...
    'y_max',0.02,'YOutline',Unco_young,'OOutline',Unco_old,...
    'CONDITIONAL','abs');
[~,~,h_UKFull_UC]=Get_Prevalence_Histogram...
    ( nVect,nTicker,kB,kL,Equil_Full,DiseaseFree,'UKFullHist_Unco','Full Model',...
    'y_max',0.02,'LEGEND','on','young_max',4,'old_max',2,'YOutline',Unco_young,'OOutline',Unco_old,...
    'CONDITIONAL','abs');